version: '3.8'

services:
  web:
    image: muhakbaryasinkpukonut/simpadi:latest
    build: .
    ports:
      - "8002:8000"
    volumes:
      # Menggunakan Named Volume terpisah untuk Database dan Media
      - simpadi_db_volume:/app/db
      - simpadi_media_volume:/app/media
    environment:
      - DEBUG=True
    # Menjalankan server tanpa melakukan otomatisasi migrasi agar tidak merusak DB asli
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  simpadi_db_volume:
  simpadi_media_volume: