# Generated by Django 4.2.30 on 2026-05-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_globalconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Menentukan apakah pengguna dapat masuk ke situs admin/operator.', verbose_name='Status Operator'),
        ),
    ]
