# Generated by Django 4.2.30 on 2026-05-10 16:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratTugas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomor_surat', models.CharField(max_length=100, unique=True, verbose_name='Nomor Surat')),
                ('perihal', models.TextField(verbose_name='Perihal')),
                ('tgl_surat', models.DateField(verbose_name='Tanggal Surat')),
                ('file_path', models.URLField(blank=True, null=True, verbose_name='Link File (Drive)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('COMPLETED', 'Selesai'), ('CANCELLED', 'Dibatalkan')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('pegawai', models.ManyToManyField(related_name='surat_tugas_set', to='master_data.pegawai', verbose_name='Pegawai Terdaftar')),
            ],
            options={
                'verbose_name': 'Surat Tugas',
                'verbose_name_plural': 'Manajemen Surat Tugas',
            },
        ),
        migrations.CreateModel(
            name='PerjalananDinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Menunggu Verifikasi'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak'), ('PROCESSED', 'Selesai Diproses')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('tempat_berangkat', models.CharField(max_length=255, verbose_name='Tempat Berangkat')),
                ('tempat_tujuan', models.CharField(max_length=255, verbose_name='Tempat Tujuan')),
                ('maksud_perjalanan', models.TextField(verbose_name='Maksud Perjalanan')),
                ('tanggal_berangkat', models.DateField(verbose_name='Tanggal Berangkat')),
                ('tanggal_kembali', models.DateField(verbose_name='Tanggal Kembali')),
                ('tahun_sbm', models.IntegerField(choices=[(2023, '2023 (Tahun Lalu)'), (2024, '2024 (Tahun Ini)')], default=2024, verbose_name='Tahun SBM')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anggaran', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.anggaran', verbose_name='Sumber Anggaran')),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.pegawai', verbose_name='Pegawai')),
                ('surat_tugas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='perjalanan.surattugas', verbose_name='Surat Tugas')),
                ('tujuan_provinsi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.provinsi', verbose_name='Provinsi (SBM)')),
            ],
            options={
                'verbose_name': 'Perjalanan Dinas',
                'verbose_name_plural': 'Data Perjalanan Dinas',
            },
        ),
        migrations.CreateModel(
            name='BiayaPerjalanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uang_harian_riil', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('uang_representasi_riil', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('biaya_penginapan_riil', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('biaya_transportasi_riil', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_dibayarkan', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('perjalanan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biaya', to='perjalanan.perjalanandinas')),
            ],
        ),
        migrations.CreateModel(
            name='BerkasPerjalanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_berkas', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='perjalanan_dinas/%Y/%m/')),
                ('google_drive_id', models.CharField(blank=True, max_length=255, null=True)),
                ('google_drive_link', models.URLField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('perjalanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='berkas', to='perjalanan.perjalanandinas')),
            ],
        ),
    ]
