# Generated by Django 4.2.30 on 2026-05-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perjalanan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perjalanandinas',
            options={'verbose_name': 'SPD (Surat Perjalanan Dinas)', 'verbose_name_plural': 'Data SPD (Terbit)'},
        ),
        migrations.AddField(
            model_name='perjalanandinas',
            name='nomor_spd',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Nomor SPD'),
        ),
        migrations.AlterField(
            model_name='perjalanandinas',
            name='tanggal_berangkat',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Berangkat'),
        ),
        migrations.AlterField(
            model_name='perjalanandinas',
            name='tanggal_kembali',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Kembali'),
        ),
        migrations.AlterField(
            model_name='perjalanandinas',
            name='tempat_berangkat',
            field=models.CharField(default='KPU Kab. Konawe Utara', max_length=255, verbose_name='Tempat Berangkat'),
        ),
    ]
