# Generated by Django 4.2.30 on 2026-05-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perjalanan', '0002_alter_perjalanandinas_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanNomorSPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix_terakhir', models.IntegerField(default=0, verbose_name='Nomor Terakhir (Angka)')),
                ('suffix_format', models.CharField(default='/PPK-PROV.026/VII/2026', max_length=100, verbose_name='Format Suffix (Belakang Nomor)')),
            ],
            options={
                'verbose_name': 'Konfigurasi Nomor SPD',
                'verbose_name_plural': 'Konfigurasi Nomor SPD',
            },
        ),
    ]
