# Generated by Django 4.2.30 on 2026-05-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perjalanan', '0003_pengaturannomorspd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perjalanandinas',
            options={'verbose_name': 'Manajemen SPD', 'verbose_name_plural': 'Manajemen SPD'},
        ),
        migrations.RemoveField(
            model_name='berkasperjalanan',
            name='google_drive_id',
        ),
        migrations.AlterField(
            model_name='berkasperjalanan',
            name='google_drive_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link Google Drive'),
        ),
    ]
