# Generated by Django 4.2.30 on 2026-05-16 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_jenisberkas'),
        ('perjalanan', '0004_alter_perjalanandinas_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berkasperjalanan',
            name='nama_berkas',
        ),
        migrations.AddField(
            model_name='berkasperjalanan',
            name='jenis_berkas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.jenisberkas', verbose_name='Jenis Berkas'),
        ),
    ]
