# Generated by Django 4.2.30 on 2026-05-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perjalanan', '0005_remove_berkasperjalanan_nama_berkas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='berkasperjalanan',
            name='nominal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Nominal Biaya'),
        ),
    ]
