# Generated by Django 4.2.30 on 2026-05-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perjalanan', '0006_berkasperjalanan_nominal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berkasperjalanan',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='perjalanan_dinas/%Y/%m/'),
        ),
    ]
