# Generated by Django 4.2.30 on 2026-05-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perjalanan', '0007_alter_berkasperjalanan_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berkasperjalanan',
            name='google_drive_link',
        ),
    ]
