# Generated by Django 4.2.30 on 2026-05-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perjalanan', '0008_remove_berkasperjalanan_google_drive_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='berkasperjalanan',
            name='keterangan',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keterangan'),
        ),
    ]
