# Generated by Django 4.2.30 on 2026-05-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perjalanan', '0009_berkasperjalanan_keterangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berkasperjalanan',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verifikasi?'),
        ),
    ]
