# Generated by Django 4.2.30 on 2026-05-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perjalanan', '0010_alter_berkasperjalanan_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='perjalanandinas',
            name='jenis_perjalanan',
            field=models.CharField(choices=[('luar_kota', 'Luar Kota'), ('dalam_kota', 'Dalam Kota (> 8 Jam)'), ('diklat', 'Diklat')], default='luar_kota', max_length=20, verbose_name='Jenis Perjalanan Dinas'),
        ),
    ]
