# Generated by Django 4.2.30 on 2026-05-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perjalanan', '0011_perjalanandinas_jenis_perjalanan'),
    ]

    operations = [
        migrations.AddField(
            model_name='biayaperjalanan',
            name='penginapan_dana_pribadi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Dana Pribadi Penginapan'),
        ),
        migrations.AddField(
            model_name='biayaperjalanan',
            name='total_dana_pribadi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Dana Pribadi'),
        ),
        migrations.AddField(
            model_name='biayaperjalanan',
            name='transportasi_dana_pribadi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Dana Pribadi Transportasi'),
        ),
    ]
