# Generated by Django 4.2.30 on 2026-05-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perjalanan', '0012_biayaperjalanan_penginapan_dana_pribadi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perjalanandinas',
            name='jenis_transportasi',
            field=models.CharField(choices=[('mobil_dinas', 'Mobil Dinas'), ('umum', 'Transportasi Umum')], default='umum', max_length=20, verbose_name='Jenis Transportasi'),
        ),
    ]
