# Generated by Django 4.2.30 on 2026-05-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perjalanan', '0013_perjalanandinas_jenis_transportasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='perjalanandinas',
            name='tidak_menginap',
            field=models.BooleanField(default=False, verbose_name='Saya tidak menginap di hotel/penginapan'),
        ),
    ]
