# Generated by Django 4.2.30 on 2026-05-18 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perjalanan', '0014_perjalanandinas_tidak_menginap'),
    ]

    operations = [
        migrations.CreateModel(
            name='BerkasPerjalananNominal',
            fields=[
            ],
            options={
                'verbose_name': 'Berkas Pendukung dengan Nominal Biaya',
                'verbose_name_plural': 'Berkas Pendukung dengan Nominal Biaya',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('perjalanan.berkasperjalanan',),
        ),
        migrations.CreateModel(
            name='BerkasPerjalananNonNominal',
            fields=[
            ],
            options={
                'verbose_name': 'Berkas Pendukung Tanpa Nominal Biaya',
                'verbose_name_plural': 'Berkas Pendukung Tanpa Nominal Biaya',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('perjalanan.berkasperjalanan',),
        ),
    ]
