# Generated by Django 4.2.30 on 2026-05-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perjalanan', '0015_berkasperjalanannominal_berkasperjalanannonnominal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berkasperjalanan',
            name='nominal',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Nominal Biaya'),
        ),
        migrations.AlterField(
            model_name='biayaperjalanan',
            name='biaya_penginapan_riil',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='biayaperjalanan',
            name='biaya_transportasi_riil',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='biayaperjalanan',
            name='penginapan_dana_pribadi',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Dana Pribadi Penginapan'),
        ),
        migrations.AlterField(
            model_name='biayaperjalanan',
            name='total_dana_pribadi',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Total Dana Pribadi'),
        ),
        migrations.AlterField(
            model_name='biayaperjalanan',
            name='total_dibayarkan',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='biayaperjalanan',
            name='transportasi_dana_pribadi',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Dana Pribadi Transportasi'),
        ),
        migrations.AlterField(
            model_name='biayaperjalanan',
            name='uang_harian_riil',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='biayaperjalanan',
            name='uang_representasi_riil',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
