# Generated by Django 4.2.30 on 2026-05-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perjalanan', '0016_alter_berkasperjalanan_nominal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perjalanandinas',
            name='tidak_menginap',
        ),
        migrations.AddField(
            model_name='berkasperjalanan',
            name='malam_menginap',
            field=models.IntegerField(blank=True, null=True, verbose_name='Malam Menginap'),
        ),
    ]
