# Generated by Django 4.2.30 on 2026-05-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perjalanan', '0017_remove_perjalanandinas_tidak_menginap_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BerkasPerjalananNominal',
        ),
        migrations.CreateModel(
            name='BerkasPerjalananPenginapan',
            fields=[
            ],
            options={
                'verbose_name': 'Berkas Pendukung untuk Penginapan',
                'verbose_name_plural': 'Berkas Pendukung untuk Penginapan',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('perjalanan.berkasperjalanan',),
        ),
        migrations.CreateModel(
            name='BerkasPerjalananTransportasi',
            fields=[
            ],
            options={
                'verbose_name': 'Berkas Pendukung untuk Transportasi',
                'verbose_name_plural': 'Berkas Pendukung untuk Transportasi',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('perjalanan.berkasperjalanan',),
        ),
        migrations.AddField(
            model_name='perjalanandinas',
            name='tidak_menginap',
            field=models.BooleanField(default=False, verbose_name='Tidak Menginap (Biaya Penginapan Rp 0)'),
        ),
    ]
