# Generated by Django 4.2.30 on 2026-05-19 16:02

from django.db import migrations


def update_jenis_berkas(apps, schema_editor):
    JenisBerkas = apps.get_model('master_data', 'JenisBerkas')
    JenisBerkas.objects.filter(
        nama__in=['SURAT PERNYATAAN TIDAK MENGINAP', 'KTP TEMPAT MENGINAP (30%)']
    ).update(kategori_biaya='penginapan')

def reverse_update_jenis_berkas(apps, schema_editor):
    JenisBerkas = apps.get_model('master_data', 'JenisBerkas')
    JenisBerkas.objects.filter(
        nama__in=['SURAT PERNYATAAN TIDAK MENGINAP', 'KTP TEMPAT MENGINAP (30%)']
    ).update(kategori_biaya='none')


class Migration(migrations.Migration):

    dependencies = [
        ('perjalanan', '0018_delete_berkasperjalanannominal_and_more'),
        ('master_data', '0007_alter_anggaran_pagu_alter_anggaran_sisa_pagu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perjalanandinas',
            name='tidak_menginap',
        ),
        migrations.RunPython(
            update_jenis_berkas,
            reverse_code=reverse_update_jenis_berkas,
        ),
    ]
