# Generated by Django 4.2.30 on 2026-05-19 16:30

from django.db import migrations


def rename_and_move_berkas(apps, schema_editor):
    JenisBerkas = apps.get_model('master_data', 'JenisBerkas')
    
    # 1. Rename SURAT PERNYATAAN TIDAK MENGINAP to TIDAK MENGINAP (remains category 'penginapan', nominal_biaya = False)
    JenisBerkas.objects.filter(nama='SURAT PERNYATAAN TIDAK MENGINAP').update(
        nama='TIDAK MENGINAP',
        kategori_biaya='penginapan',
        nominal_biaya=False
    )
    
    # 2. Rename KTP TEMPAT MENGINAP (30%) to KTP TEMPAT MENGINAP and move to 'none' (nominal_biaya = False)
    JenisBerkas.objects.filter(nama='KTP TEMPAT MENGINAP (30%)').update(
        nama='KTP TEMPAT MENGINAP',
        kategori_biaya='none',
        nominal_biaya=False
    )

def reverse_rename_and_move_berkas(apps, schema_editor):
    JenisBerkas = apps.get_model('master_data', 'JenisBerkas')
    
    # Restore nominal_biaya to original state (whatever it was, say True for SURAT PERNYATAAN TIDAK MENGINAP)
    JenisBerkas.objects.filter(nama='TIDAK MENGINAP').update(
        nama='SURAT PERNYATAAN TIDAK MENGINAP',
        kategori_biaya='penginapan',
        nominal_biaya=True
    )
    
    JenisBerkas.objects.filter(nama='KTP TEMPAT MENGINAP').update(
        nama='KTP TEMPAT MENGINAP (30%)',
        kategori_biaya='penginapan',
        nominal_biaya=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ('perjalanan', '0019_remove_perjalanandinas_tidak_menginap'),
    ]

    operations = [
        migrations.RunPython(
            rename_and_move_berkas,
            reverse_code=reverse_rename_and_move_berkas,
        ),
    ]
