# Generated by Django 4.2.30 on 2026-05-20 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0010_alter_jenisberkas_kategori_biaya'),
        ('perjalanan', '0022_alter_perjalanandinas_jenis_perjalanan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perjalanandinas',
            name='anggaran',
        ),
        migrations.RemoveField(
            model_name='perjalanandinas',
            name='jenis_perjalanan',
        ),
        migrations.RemoveField(
            model_name='perjalanandinas',
            name='jenis_transportasi',
        ),
        migrations.RemoveField(
            model_name='perjalanandinas',
            name='maksud_perjalanan',
        ),
        migrations.RemoveField(
            model_name='perjalanandinas',
            name='tahun_sbm',
        ),
        migrations.RemoveField(
            model_name='perjalanandinas',
            name='tanggal_berangkat',
        ),
        migrations.RemoveField(
            model_name='perjalanandinas',
            name='tanggal_kembali',
        ),
        migrations.RemoveField(
            model_name='perjalanandinas',
            name='tempat_berangkat',
        ),
        migrations.RemoveField(
            model_name='perjalanandinas',
            name='tempat_tujuan',
        ),
        migrations.RemoveField(
            model_name='perjalanandinas',
            name='tujuan_provinsi',
        ),
        migrations.AddField(
            model_name='surattugas',
            name='anggaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.anggaran', verbose_name='Sumber Anggaran'),
        ),
        migrations.AddField(
            model_name='surattugas',
            name='jenis_perjalanan',
            field=models.CharField(choices=[('luar_kota', 'Luar Kota'), ('dalam_kota', 'Dalam Kota (> 8 Jam)'), ('diklat', 'Diklat')], default='luar_kota', max_length=20, verbose_name='Jenis Perjalanan Dinas'),
        ),
        migrations.AddField(
            model_name='surattugas',
            name='jenis_transportasi',
            field=models.CharField(choices=[('mobil_dinas', 'Mobil Dinas'), ('umum', 'Transportasi Umum')], default='umum', max_length=20, verbose_name='Jenis Transportasi'),
        ),
        migrations.AddField(
            model_name='surattugas',
            name='maksud_perjalanan',
            field=models.TextField(blank=True, null=True, verbose_name='Maksud Perjalanan'),
        ),
        migrations.AddField(
            model_name='surattugas',
            name='tahun_sbm',
            field=models.IntegerField(choices=[(2023, '2023 (Tahun Lalu)'), (2024, '2024 (Tahun Ini)')], default=2024, verbose_name='Tahun SBM'),
        ),
        migrations.AddField(
            model_name='surattugas',
            name='tanggal_berangkat',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Berangkat'),
        ),
        migrations.AddField(
            model_name='surattugas',
            name='tanggal_kembali',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Kembali'),
        ),
        migrations.AddField(
            model_name='surattugas',
            name='tempat_berangkat',
            field=models.CharField(default='KPU Kab. Konawe Utara', max_length=255, verbose_name='Tempat Berangkat'),
        ),
        migrations.AddField(
            model_name='surattugas',
            name='tempat_tujuan',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tempat Tujuan'),
        ),
        migrations.AddField(
            model_name='surattugas',
            name='tujuan_provinsi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.provinsi', verbose_name='Provinsi (SBM)'),
        ),
    ]
