# Generated by Django 4.2.30 on 2026-05-20 21:08

import django.core.validators
from django.db import migrations, models
import perjalanan.models


class Migration(migrations.Migration):

    dependencies = [
        ('perjalanan', '0023_remove_perjalanandinas_anggaran_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surattugas',
            name='file_path',
            field=models.FileField(default='', upload_to=perjalanan.models.upload_surat_tugas_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='File Surat Tugas (PDF)'),
            preserve_default=False,
        ),
    ]
