# Generated by Django 4.2.30 on 2026-05-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perjalanan', '0024_alter_surattugas_file_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perjalanandinas',
            options={'verbose_name': 'Surat Perjalanan Dinas', 'verbose_name_plural': 'Surat Perjalanan Dinas'},
        ),
    ]
