# Generated by Django 4.2.30 on 2026-05-22 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0014_alter_jenisberkas_kategori_biaya'),
        ('perjalanan', '0025_alter_perjalanandinas_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarianPerjalanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari_ke', models.PositiveIntegerField(verbose_name='Hari Ke')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('jenis_harian', models.CharField(choices=[('normal', 'Uang Harian Normal'), ('fullboard_luar', 'Fullboard Luar Kota'), ('fullboard_dalam', 'Fullboard Dalam Kota')], default='normal', max_length=20)),
                ('perjalanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harian_details', to='perjalanan.perjalanandinas')),
                ('provinsi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.provinsi', verbose_name='Provinsi')),
            ],
            options={
                'ordering': ['hari_ke'],
                'unique_together': {('perjalanan', 'hari_ke')},
            },
        ),
    ]
