# Generated by Django 4.2.30 on 2026-05-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perjalanan', '0026_harianperjalanan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harianperjalanan',
            name='jenis_harian',
            field=models.CharField(choices=[('luar_kota', 'Luar Kota'), ('dalam_kota', 'Dalam Kota (> 8 Jam)'), ('diklat', 'Diklat'), ('halfday', 'Rapat/Pertemuan Halfday'), ('fullday', 'Rapat/Pertemuan Fullday'), ('fullboard', 'Rapat/Pertemuan Fullboard')], default='luar_kota', max_length=20),
        ),
    ]
