# Generated by Django 4.2.30 on 2026-05-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perjalanan', '0028_alter_harianperjalanan_jenis_harian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harianperjalanan',
            name='jenis_harian',
            field=models.CharField(choices=[('luar_kota', 'Luar Kota'), ('dalam_kota', 'Dalam Kota (> 8 Jam)'), ('diklat', 'Diklat'), ('halfday', 'Rapat/Pertemuan Halfday'), ('fullday', 'Rapat/Pertemuan Fullday'), ('fullboard', 'Rapat/Pertemuan Fullboard'), ('tidak_dibayai', 'Tidak Dibiayai (Bentrok)')], default='luar_kota', max_length=20, verbose_name='Jenis Perjalanan Dinas'),
        ),
    ]
