# Generated by Django 4.2.30 on 2026-05-23 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perjalanan', '0029_alter_harianperjalanan_jenis_harian'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perjalanandinas',
            options={},
        ),
        migrations.CreateModel(
            name='StatusHistoryPerjalanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Menunggu Verifikasi'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak'), ('PROCESSED', 'Selesai Diproses')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('perjalanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='perjalanan.perjalanandinas')),
            ],
            options={
                'verbose_name': 'Riwayat Status Perjalanan',
                'verbose_name_plural': 'Riwayat Status Perjalanan',
                'ordering': ['created_at'],
            },
        ),
    ]
