# Generated by Django 4.2.30 on 2026-05-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perjalanan', '0030_alter_perjalanandinas_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surattugas',
            name='tahun_sbm',
            field=models.IntegerField(default=2024, verbose_name='Tahun SBM'),
        ),
    ]
