# Generated by Django 4.2.30 on 2026-05-10 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anggaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_dipa', models.CharField(max_length=50, unique=True, verbose_name='Kode DIPA')),
                ('nama_kegiatan', models.CharField(max_length=255, verbose_name='Nama Kegiatan')),
                ('pagu', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Pagu')),
                ('sisa_pagu', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Sisa Pagu')),
            ],
            options={
                'verbose_name': 'Anggaran',
                'verbose_name_plural': 'Data Anggaran',
            },
        ),
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Provinsi',
                'verbose_name_plural': 'Data Provinsi',
            },
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=20, unique=True, verbose_name='NIP')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Lengkap')),
                ('golongan', models.CharField(choices=[('I', 'Golongan I'), ('II', 'Golongan II'), ('III', 'Golongan III'), ('IV', 'Golongan IV')], max_length=5, verbose_name='Golongan')),
                ('jabatan', models.CharField(max_length=100, verbose_name='Jabatan')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pegawai_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pegawai',
                'verbose_name_plural': 'Data Pegawai',
            },
        ),
        migrations.CreateModel(
            name='StandarBiaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golongan', models.CharField(choices=[('I', 'Golongan I'), ('II', 'Golongan II'), ('III', 'Golongan III'), ('IV', 'Golongan IV')], max_length=5)),
                ('uang_harian', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Uang Harian')),
                ('plafon_penginapan', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Plafon Penginapan')),
                ('uang_representasi', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Uang Representasi')),
                ('tahun', models.IntegerField(choices=[(2023, '2023 (Tahun Lalu)'), (2024, '2024 (Tahun Ini)')], default=2024, verbose_name='Tahun')),
                ('provinsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.provinsi')),
            ],
            options={
                'verbose_name': 'Standar Biaya (SBM)',
                'verbose_name_plural': 'Standar Biaya (SBM)',
                'unique_together': {('provinsi', 'golongan', 'tahun')},
            },
        ),
    ]
