# Generated by Django 4.2.30 on 2026-05-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_pegawai_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisBerkas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True, verbose_name='Nama Jenis Berkas')),
                ('wajib', models.BooleanField(default=False, verbose_name='Wajib Diunggah?')),
            ],
            options={
                'verbose_name': 'Jenis Berkas',
                'verbose_name_plural': 'Master Jenis Berkas',
            },
        ),
    ]
