# Generated by Django 4.2.30 on 2026-05-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_jenisberkas'),
    ]

    operations = [
        migrations.CreateModel(
            name='PejabatPenandatangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150, verbose_name='Nama Lengkap')),
                ('nip', models.CharField(max_length=30, verbose_name='NIP')),
                ('jabatan', models.CharField(choices=[('SEKRETARIS', 'Sekretaris'), ('PPK', 'Pejabat Pembuat Komitmen (PPK)')], max_length=50, verbose_name='Jabatan')),
                ('aktif', models.BooleanField(default=True, verbose_name='Status Aktif')),
            ],
            options={
                'verbose_name': 'Pejabat Penandatangan',
                'verbose_name_plural': 'Pejabat Penandatangan',
            },
        ),
        migrations.AlterModelOptions(
            name='jenisberkas',
            options={'verbose_name': 'Jenis Berkas', 'verbose_name_plural': 'Jenis Berkas'},
        ),
    ]
