# Generated by Django 4.2.30 on 2026-05-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_pejabatpenandatangan_alter_jenisberkas_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenisberkas',
            name='nominal_biaya',
            field=models.BooleanField(default=False, verbose_name='Menyertakan Nominal Biaya?'),
        ),
    ]
