# Generated by Django 4.2.30 on 2026-05-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_jenisberkas_nominal_biaya'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenisberkas',
            name='kategori_biaya',
            field=models.CharField(choices=[('penginapan', 'Biaya Penginapan'), ('transportasi', 'Biaya Transportasi'), ('none', 'Bukan Biaya (Lain-lain)')], default='none', max_length=20, verbose_name='Kategori Biaya'),
        ),
        migrations.AddField(
            model_name='standarbiaya',
            name='plafon_transportasi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Plafon Transportasi'),
        ),
    ]
