# Generated by Django 4.2.30 on 2026-05-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_jenisberkas_kategori_biaya_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggaran',
            name='pagu',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Total Pagu'),
        ),
        migrations.AlterField(
            model_name='anggaran',
            name='sisa_pagu',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Sisa Pagu'),
        ),
        migrations.AlterField(
            model_name='standarbiaya',
            name='plafon_penginapan',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Plafon Penginapan'),
        ),
        migrations.AlterField(
            model_name='standarbiaya',
            name='plafon_transportasi',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Plafon Transportasi'),
        ),
        migrations.AlterField(
            model_name='standarbiaya',
            name='uang_harian',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Uang Harian'),
        ),
        migrations.AlterField(
            model_name='standarbiaya',
            name='uang_representasi',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Uang Representasi'),
        ),
    ]
