# Generated by Django 4.2.30 on 2026-05-19 19:44

from django.db import migrations, models


def update_tidak_menginap_category(apps, schema_editor):
    JenisBerkas = apps.get_model('master_data', 'JenisBerkas')
    JenisBerkas.objects.filter(nama='TIDAK MENGINAP').update(
        kategori_biaya='penginapan_30',
        nominal_biaya=False
    )

def reverse_tidak_menginap_category(apps, schema_editor):
    JenisBerkas = apps.get_model('master_data', 'JenisBerkas')
    JenisBerkas.objects.filter(nama='TIDAK MENGINAP').update(
        kategori_biaya='penginapan',
        nominal_biaya=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_alter_anggaran_pagu_alter_anggaran_sisa_pagu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenisberkas',
            name='kategori_biaya',
            field=models.CharField(choices=[('penginapan', 'Biaya Penginapan'), ('penginapan_30', 'Biaya Penginapan 30%'), ('transportasi', 'Biaya Transportasi'), ('none', 'Bukan Biaya (Lain-lain)')], default='none', max_length=20, verbose_name='Kategori Biaya'),
        ),
        migrations.RunPython(update_tidak_menginap_category, reverse_code=reverse_tidak_menginap_category),
    ]
