# Generated by Django 4.2.30 on 2026-05-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0008_alter_jenisberkas_kategori_biaya'),
    ]

    operations = [
        migrations.AddField(
            model_name='standarbiaya',
            name='uang_harian_fullboard_dalam',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Uang Harian Fullboard Dalam Kota'),
        ),
        migrations.AddField(
            model_name='standarbiaya',
            name='uang_harian_fullboard_luar',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Uang Harian Fullboard Luar Kota'),
        ),
    ]
