# Generated by Django 4.2.30 on 2026-05-20 17:56

from django.db import migrations, models


def seed_jenis_berkas(apps, schema_editor):
    JenisBerkas = apps.get_model('master_data', 'JenisBerkas')
    JenisBerkas.objects.get_or_create(
        nama='BIAYA PENGINAPAN FULLBOARD LUAR KOTA',
        defaults={
            'kategori_biaya': 'penginapan_fb_luar',
            'nominal_biaya': False,
            'wajib': False
        }
    )
    JenisBerkas.objects.get_or_create(
        nama='BIAYA PENGINAPAN FULLBOARD DALAM KOTA',
        defaults={
            'kategori_biaya': 'penginapan_fb_dalam',
            'nominal_biaya': False,
            'wajib': False
        }
    )


def remove_jenis_berkas(apps, schema_editor):
    JenisBerkas = apps.get_model('master_data', 'JenisBerkas')
    JenisBerkas.objects.filter(nama__in=[
        'BIAYA PENGINAPAN FULLBOARD LUAR KOTA',
        'BIAYA PENGINAPAN FULLBOARD DALAM KOTA'
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_standarbiaya_uang_harian_fullboard_dalam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenisberkas',
            name='kategori_biaya',
            field=models.CharField(choices=[('penginapan', 'Biaya Penginapan'), ('penginapan_30', 'Biaya Penginapan 30%'), ('penginapan_fb_luar', 'Biaya Penginapan Fullboard Luar Kota'), ('penginapan_fb_dalam', 'Biaya Penginapan Fullboard Dalam Kota'), ('transportasi', 'Biaya Transportasi'), ('none', 'Bukan Biaya (Lain-lain)')], default='none', max_length=30, verbose_name='Kategori Biaya'),
        ),
        migrations.RunPython(seed_jenis_berkas, reverse_code=remove_jenis_berkas),
    ]
