# Generated by Django 4.2.30 on 2026-05-20 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0010_alter_jenisberkas_kategori_biaya'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standarbiaya',
            options={'verbose_name': 'Standar Biaya Masukan (SBM) / Provinsi', 'verbose_name_plural': 'Standar Biaya Masukan (SBM) / Provinsi'},
        ),
    ]
