# Generated by Django 4.2.30 on 2026-05-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0011_alter_standarbiaya_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandarBiayaTiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kota_asal', models.CharField(max_length=100, verbose_name='Kota Asal')),
                ('kota_tujuan', models.CharField(max_length=100, verbose_name='Kota Tujuan')),
                ('kelas', models.CharField(choices=[('bisnis', 'Bisnis'), ('ekonomi', 'Ekonomi')], max_length=10, verbose_name='Kelas Tiket')),
                ('nominal', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Nominal Biaya (PP)')),
            ],
            options={
                'verbose_name': 'Standar Biaya Masukan (SBM) Tiket Pesawat Dalam Negeri',
                'verbose_name_plural': 'Standar Biaya Masukan (SBM) Tiket Pesawat Dalam Negeri',
                'ordering': ['kota_asal', 'kota_tujuan', 'kelas'],
                'unique_together': {('kota_asal', 'kota_tujuan', 'kelas')},
            },
        ),
    ]
