# Generated by Django 4.2.30 on 2026-05-20 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0012_standarbiayatiket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standarbiayatiket',
            options={'ordering': ['kota_asal__nama', 'kota_tujuan__nama', 'kelas'], 'verbose_name': 'Standar Biaya Masukan (SBM) Tiket Pesawat Dalam Negeri', 'verbose_name_plural': 'Standar Biaya Masukan (SBM) Tiket Pesawat Dalam Negeri'},
        ),
        migrations.CreateModel(
            name='Kota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Kota/Kabupaten')),
                ('provinsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kota_set', to='master_data.provinsi', verbose_name='Provinsi')),
            ],
            options={
                'verbose_name': 'Kota/Kabupaten',
                'verbose_name_plural': 'Data Kota/Kabupaten',
                'ordering': ['provinsi__nama', 'nama'],
                'unique_together': {('provinsi', 'nama')},
            },
        ),
        migrations.AlterField(
            model_name='standarbiayatiket',
            name='kota_asal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiket_asal_set', to='master_data.kota', verbose_name='Kota Asal'),
        ),
        migrations.AlterField(
            model_name='standarbiayatiket',
            name='kota_tujuan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiket_tujuan_set', to='master_data.kota', verbose_name='Kota Tujuan'),
        ),
    ]
