# Generated by Django 4.2.30 on 2026-05-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0013_alter_standarbiayatiket_options_kota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenisberkas',
            name='kategori_biaya',
            field=models.CharField(choices=[('penginapan', 'Biaya Penginapan'), ('penginapan_30', 'Biaya Penginapan 30%'), ('penginapan_fb_luar', 'Biaya Penginapan Fullboard Luar Kota'), ('penginapan_fb_dalam', 'Biaya Penginapan Fullboard Dalam Kota'), ('transportasi', 'Biaya Transportasi'), ('transportasi_pesawat', 'Biaya Transportasi Tiket Pesawat'), ('none', 'Bukan Biaya (Lain-lain)')], default='none', max_length=30, verbose_name='Kategori Biaya'),
        ),
    ]
