# Generated by Django 4.2.30 on 2026-05-24 04:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0014_alter_jenisberkas_kategori_biaya'),
    ]

    operations = [
        migrations.CreateModel(
            name='DokumenSBM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField(unique=True, verbose_name='Tahun SBM')),
                ('file_pdf', models.FileField(upload_to='sbm_dokumen/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='File PDF SBM')),
            ],
            options={
                'verbose_name': 'Dokumen SBM',
                'verbose_name_plural': 'Dokumen SBM',
                'ordering': ['-tahun'],
            },
        ),
        migrations.AlterField(
            model_name='standarbiaya',
            name='tahun',
            field=models.IntegerField(default=2024, verbose_name='Tahun'),
        ),
    ]
