# Generated by Django 4.2.30 on 2026-05-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0015_dokumensbm_alter_standarbiaya_tahun'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standarbiayatiket',
            options={'ordering': ['kota_asal__nama', 'kota_tujuan__nama', 'kelas', 'tahun'], 'verbose_name': 'Standar Biaya Masukan (SBM) Tiket Pesawat Dalam Negeri', 'verbose_name_plural': 'Standar Biaya Masukan (SBM) Tiket Pesawat Dalam Negeri'},
        ),
        migrations.AlterUniqueTogether(
            name='standarbiayatiket',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='standarbiayatiket',
            name='tahun',
            field=models.IntegerField(default=2024, verbose_name='Tahun'),
        ),
        migrations.AlterUniqueTogether(
            name='standarbiayatiket',
            unique_together={('kota_asal', 'kota_tujuan', 'kelas', 'tahun')},
        ),
    ]
