# Generated by Django 4.2.30 on 2026-05-24 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0016_alter_standarbiayatiket_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dokumensbm',
            options={'ordering': ['-tahun'], 'verbose_name': 'Tahun Standar Biaya Masukan (SBM)', 'verbose_name_plural': 'Tahun Standar Biaya Masukan (SBM)'},
        ),
    ]
