# Generated by Django 4.2.30 on 2026-05-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0017_alter_dokumensbm_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawai',
            name='posisi_jabatan',
            field=models.CharField(choices=[('NON_ESELON', 'Non Posisi Eselon'), ('ES_IV', 'Eselon IV'), ('ES_III', 'Eselon III'), ('ES_II', 'Eselon II')], default='NON_ESELON', max_length=15, verbose_name='Posisi Jabatan'),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='golongan',
            field=models.CharField(choices=[('I', 'Golongan I'), ('II', 'Golongan II'), ('III', 'Golongan III'), ('IV', 'Golongan IV'), ('ES_II', 'Eselon II'), ('ES_III', 'Eselon III'), ('ES_IV', 'Eselon IV')], max_length=15, verbose_name='Golongan'),
        ),
        migrations.AlterField(
            model_name='standarbiaya',
            name='golongan',
            field=models.CharField(choices=[('I', 'Golongan I'), ('II', 'Golongan II'), ('III', 'Golongan III'), ('IV', 'Golongan IV'), ('ES_II', 'Eselon II'), ('ES_III', 'Eselon III'), ('ES_IV', 'Eselon IV')], max_length=15),
        ),
    ]
