# Generated by Django 4.2.30 on 2026-05-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0018_pegawai_posisi_jabatan_alter_pegawai_golongan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standarbiayatiket',
            options={'ordering': ['kota_asal__nama', 'kota_tujuan__nama', 'kelas', 'golongan', 'posisi_jabatan', 'tahun'], 'verbose_name': 'Standar Biaya Masukan (SBM) Tiket Pesawat Dalam Negeri', 'verbose_name_plural': 'Standar Biaya Masukan (SBM) Tiket Pesawat Dalam Negeri'},
        ),
        migrations.AlterUniqueTogether(
            name='standarbiaya',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='standarbiayatiket',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='standarbiaya',
            name='posisi_jabatan',
            field=models.CharField(blank=True, choices=[('NON_ESELON', 'Non Posisi Eselon'), ('ES_IV', 'Eselon IV'), ('ES_III', 'Eselon III'), ('ES_II', 'Eselon II')], max_length=15, null=True, verbose_name='Posisi Jabatan'),
        ),
        migrations.AddField(
            model_name='standarbiayatiket',
            name='golongan',
            field=models.CharField(blank=True, choices=[('I', 'Golongan I'), ('II', 'Golongan II'), ('III', 'Golongan III'), ('IV', 'Golongan IV'), ('ES_II', 'Eselon II'), ('ES_III', 'Eselon III'), ('ES_IV', 'Eselon IV')], max_length=15, null=True, verbose_name='Golongan'),
        ),
        migrations.AddField(
            model_name='standarbiayatiket',
            name='posisi_jabatan',
            field=models.CharField(blank=True, choices=[('NON_ESELON', 'Non Posisi Eselon'), ('ES_IV', 'Eselon IV'), ('ES_III', 'Eselon III'), ('ES_II', 'Eselon II')], max_length=15, null=True, verbose_name='Posisi Jabatan'),
        ),
        migrations.AlterField(
            model_name='standarbiaya',
            name='golongan',
            field=models.CharField(blank=True, choices=[('I', 'Golongan I'), ('II', 'Golongan II'), ('III', 'Golongan III'), ('IV', 'Golongan IV'), ('ES_II', 'Eselon II'), ('ES_III', 'Eselon III'), ('ES_IV', 'Eselon IV')], max_length=15, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='standarbiaya',
            unique_together={('provinsi', 'golongan', 'posisi_jabatan', 'tahun')},
        ),
        migrations.AlterUniqueTogether(
            name='standarbiayatiket',
            unique_together={('kota_asal', 'kota_tujuan', 'kelas', 'golongan', 'posisi_jabatan', 'tahun')},
        ),
    ]
