# Generated by Django 4.2.30 on 2026-05-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0019_alter_standarbiayatiket_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawai',
            name='golongan',
            field=models.CharField(choices=[('I', 'Golongan I'), ('II', 'Golongan II'), ('III', 'Golongan III'), ('IV', 'Golongan IV'), ('NON_GOLONGAN', 'Non Golongan')], max_length=15, verbose_name='Golongan'),
        ),
        migrations.AlterField(
            model_name='standarbiaya',
            name='golongan',
            field=models.CharField(blank=True, choices=[('I', 'Golongan I'), ('II', 'Golongan II'), ('III', 'Golongan III'), ('IV', 'Golongan IV'), ('NON_GOLONGAN', 'Non Golongan')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='standarbiayatiket',
            name='golongan',
            field=models.CharField(blank=True, choices=[('I', 'Golongan I'), ('II', 'Golongan II'), ('III', 'Golongan III'), ('IV', 'Golongan IV'), ('NON_GOLONGAN', 'Non Golongan')], max_length=15, null=True, verbose_name='Golongan'),
        ),
    ]
