# Generated by Django 4.2.30 on 2026-05-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0020_alter_pegawai_golongan_alter_standarbiaya_golongan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standarbiaya',
            name='uang_harian_fullboard_dalam',
        ),
        migrations.RemoveField(
            model_name='standarbiaya',
            name='uang_harian_fullboard_luar',
        ),
        migrations.AddField(
            model_name='standarbiaya',
            name='uang_harian_dalam_kota',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Uang Harian Dalam Kota (> 8 Jam)'),
        ),
        migrations.AddField(
            model_name='standarbiaya',
            name='uang_harian_diklat',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Uang Harian Diklat'),
        ),
        migrations.AlterField(
            model_name='standarbiaya',
            name='uang_harian',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Uang Harian Luar Kota'),
        ),
    ]
