# Generated by Django 4.2.30 on 2026-05-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0021_remove_standarbiaya_uang_harian_fullboard_dalam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standarbiaya',
            name='biaya_taksi',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Nominal Biaya Taksi Bandara'),
        ),
    ]
