# Generated by Django 4.2.30 on 2026-05-24 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0022_standarbiaya_biaya_taksi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standarbiaya',
            name='plafon_transportasi',
        ),
    ]
