# Generated by Django 4.2.30 on 2026-05-24 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0023_remove_standarbiaya_plafon_transportasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standarbiaya',
            name='uang_harian',
        ),
        migrations.RemoveField(
            model_name='standarbiaya',
            name='uang_harian_dalam_kota',
        ),
        migrations.RemoveField(
            model_name='standarbiaya',
            name='uang_harian_diklat',
        ),
        migrations.AlterField(
            model_name='standarbiaya',
            name='biaya_taksi',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Taksi Bandara'),
        ),
        migrations.CreateModel(
            name='StandarBiayaHarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField(default=2024, verbose_name='Tahun')),
                ('uang_harian', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Uang Harian Luar Kota')),
                ('uang_harian_dalam_kota', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Uang Harian Dalam Kota (> 8 Jam)')),
                ('uang_harian_diklat', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Uang Harian Diklat')),
                ('provinsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.provinsi')),
            ],
            options={
                'verbose_name': 'Standar Biaya Masukan (SBM) Uang Harian',
                'verbose_name_plural': 'Standar Biaya Masukan (SBM) Uang Harian',
                'unique_together': {('provinsi', 'tahun')},
            },
        ),
    ]
