# Generated by Django 4.2.30 on 2026-05-24 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0024_remove_standarbiaya_uang_harian_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standarbiaya',
            options={'verbose_name': 'Standar Biaya Masukan (SBM) Golongan/Pejabat Eselon', 'verbose_name_plural': 'Standar Biaya Masukan (SBM) Golongan/Pejabat Eselon'},
        ),
        migrations.AlterModelOptions(
            name='standarbiayatiket',
            options={'ordering': ['kota_asal__nama', 'kota_tujuan__nama', 'kelas', 'posisi_jabatan', 'tahun'], 'verbose_name': 'Standar Biaya Masukan (SBM) Tiket Pesawat Dalam Negeri', 'verbose_name_plural': 'Standar Biaya Masukan (SBM) Tiket Pesawat Dalam Negeri'},
        ),
        migrations.AlterUniqueTogether(
            name='standarbiayatiket',
            unique_together={('kota_asal', 'kota_tujuan', 'kelas', 'posisi_jabatan', 'tahun')},
        ),
        migrations.RemoveField(
            model_name='standarbiayatiket',
            name='golongan',
        ),
    ]
