# Generated by Django 4.2.30 on 2026-05-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0026_rename_uang_representasi_and_add_dalam_kota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pejabatpenandatangan',
            name='jabatan',
            field=models.CharField(choices=[('SEKRETARIS', 'Sekretaris'), ('PPK', 'Pejabat Pembuat Komitmen (PPK)'), ('BENDAHARA', 'Bendahara')], max_length=50, verbose_name='Jabatan'),
        ),
        migrations.AlterField(
            model_name='standarbiaya',
            name='uang_representasi_dalam_kota',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Representasi Dalam Kota (> 8 Jam)'),
        ),
        migrations.AlterField(
            model_name='standarbiaya',
            name='uang_representasi_luar_kota',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Representasi Luar Kota'),
        ),
    ]
