# Generated by Django 4.2.30 on 2026-05-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0027_alter_pejabatpenandatangan_jabatan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawai',
            name='nip',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='NIP'),
        ),
    ]
